### ISSUE TITLE
I'm getting a TypeError in numpy call?

### ISSUE THREAD

**Issue by gingerbeardman** [6o6o/fft-descreen#2]
I'm not familiar with `numpy` and am wondering if I need to make changes for the latest version, given you probably wrote this python using an older version of it?

```
matt$ python descreen.py images/tubingen_orig.png images/out.png
Traceback (most recent call last):
  File "descreen.py", line 36, in <module>
    middle = np.pad(ellipse(ew, eh), ((ph,rows-ph-eh*2-1), (pw,cols-pw-ew*2-1)), 'constant')
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 1298, in pad
    raise TypeError('`pad_width` must be of integral type.')
TypeError: `pad_width` must be of integral type.
```

Any help appreciated!

**Comment by 6o6o** [comment]
Hi. This is because you are using python 3. I tested it on python 2 only. I'll make it cross-compatible when I have some free time. As a temporary fix you may replace division operator `/` with `//` on lines 34 and 35, but I cannot guarantee full integrity atm.

**Comment by gingerbeardman** [comment]
Strange that python3 is mapped to python, I had always been told it was python 2.7 on macOS

Thanks for the hint - I have got it running! 

this image is with default fft-descreen settings, and max-noise artwork waifu2x via [waifu2x.udp.jp](http://waifu2x.udp.jp)

![out_waifu2x_art_noise3_tta_1](https://user-images.githubusercontent.com/49612/38393818-f81e2910-3923-11e8-891d-8b33af4a9995.png)

**Comment by 6o6o** [comment]
Glad to help. Good luck.
